---
title: "Soziale Netzwerkanalyse: IPBES"
author: "Jonas Geschke"
date: "2018"
header-includes:
   - \usepackage{longtable}
output:
  pdf_document:
    toc: yes
  documentclass: article
  html_document:
    toc: yes
  classoption: a4paper
  graphics: yes
---

# Einleitung
Dieses ist das Skript der Netzwerkanalyse zu IPBES auf Grundlage der bisher abgeschlossenen IPBES Assessments. Das Skrpit ist verfügbar unter https://github.com/JonasGeschke/nefo
Die Netzwerkanalyse selbst ist verfügbar unter XXX


# Einstellungen

```{r set wd - CHOOSE, eval=FALSE}
# If your working directory is not already specified because you are running this
# script within a project, you will need to use the setwd() function below to set
# the path of your working directory. In order to do this just copy the path
# between the quote signs.
# Please note: The different levels of the path need to be separated by slashes
# ("/"), not by backslashes ("\") which are the windows default.
# 
# setwd("")

#setwd("/Volumes/NO NAME/MfN/Netzwerkanalyse_IPBES/R") # Stick
setwd("Z:/Benutzer/Jonas.Geschke/Netzwerkanalyse_IPBES/R") # Buero
```

```{r install packages, eval=FALSE}
# Installing required packages if not installed yet
if("statnet" %in% rownames(installed.packages())   == FALSE){
  install.packages("statnet")}
if("network" %in% rownames(installed.packages())   == FALSE){
  install.packages("network")}
if("sna" %in% rownames(installed.packages())   == FALSE){
  install.packages("sna")}
if("igraph" %in% rownames(installed.packages())   == FALSE){
  install.packages("igraph")}
if("xts" %in% rownames(installed.packages())   == FALSE){
  install.packages("xts")}
if("xlsx" %in% rownames(installed.packages())   == FALSE){
  install.packages("xlsx")}
if("dplyr" %in% rownames(installed.packages())   == FALSE){
  install.packages("dplyr")}
if("rgl" %in% rownames(installed.packages())   == FALSE){
  install.packages("rgl")}
if("extrafont" %in% rownames(installed.packages())   == FALSE){
  install.packages("extrafont")}
if("circlize" %in% rownames(installed.packages())   == FALSE){
  install.packages("circlize")}
if("RColorBrewer" %in% rownames(installed.packages())   == FALSE){
  install.packages("RColorBrewer")}
if("countrycode" %in% rownames(installed.packages())   == FALSE){
  install.packages("countrycode")}
if("rworldmap" %in% rownames(installed.packages())   == FALSE){
  install.packages("rworldmap")}
```

```{r set additional functions #####EDIT#####, eval=FALSE}
as.numeric.factor <- function(x) {as.numeric(levels(x))[x]}

'%!in%' <- function(x,y)!('%in%'(x,y))

delete.isolates <- function(graph, mode = "all"){
  isolates <- which(degree(graph, mode = mode) == 0)
  delete.vertices(graph, isolates)
}

create_nodes_forschungsnetzwerke_1mode <- function(Gdata){
    w1 <- colnames(Gdata)
    w2 <- rownames(Gdata)
    w3 <- c(paste("net", c(1:ncol(Gdata)), sep = ""))
    w4 <- c(paste("inst", c(1:nrow(Gdata)), sep = ""))
    
    nodes <- as.data.frame(cbind(w4, w2))
    names(nodes) <- c("id", "name")
    nodes$id <- as.character(nodes$id)
    nodes$name <- as.character(nodes$name)
    
    return(nodes)
}

create_links_forschungsnetzwerke_1mode <- function(Gdata){
    w1 <- colnames(Gdata)
    w2 <- rownames(Gdata)
    w3 <- c(paste("net", c(1:ncol(Gdata)), sep = ""))
    w4 <- c(paste("inst", c(1:nrow(Gdata)), sep = ""))
      
    columns_Gdata <- c(1:ncol(Gdata))
    rows_Gdata <- c(1:nrow(Gdata))
    
    links_w <- data.frame(from=character(), to=character(), 
                          network_no=character(), network=character(),
                          stringsAsFactors = FALSE)
     for (c in columns_Gdata){
      for (r in rows_Gdata){
        if (as.numeric(Gdata[r,c]) == 1) {
          links_w <- rbind(links_w,
                           c(w3[c], w4[r], as.numeric(c), colnames(Gdata)[c]), 
                           stringsAsFactors = FALSE)
        } else {}
      }
    }
    
    colnames(links_w) <- c("links_w_1", "links_w_2", "links_w_3", "links_w_4")
    
    links <- data.frame(from=character(), to=character(), 
                        network_no=character(), network=character(),
                        stringsAsFactors = FALSE)
    
    for(n in columns_Gdata){
      subset <- subset(links_w, links_w$links_w_4 == w1[n])
      rowssubset <- c(1:nrow(subset))
      for (r in rowssubset){
        t <- 1
        repeat{
          links <- rbind(links,
                         c(subset[r,2], subset[r+t,2], n, paste(w1[n])),
                         stringsAsFactors = FALSE)
          t <- t+1
          if (t==max(rowssubset)){break}}
      }
    }
    
    colnames(links) <- c("from", "to", "network_no", "network")
    links$network_no <- as.numeric(links$network_no)
    links <- subset(links, !is.na(links$to))
    
    return(links)
}
```


# Rohdaten

```{r Laden der Rohdaten, eval=FALSE}
## Load raw data
Raw_authors <- xlsx::read.xlsx(file = "IPBES_authors.xlsx", sheetIndex = 1, encoding="UTF-8")
Raw_authors$CC <- as.factor(countrycode::countrycode(Raw_authors$Country, origin = "country.name", destination = "genc2c"))

authors <- Raw_authors
authors$Name <- as.character(authors$Name)
str(authors)
authors$unique <- apply(authors[,c(3,5)], 1, paste, collapse = " _ ")
authors$aut_id <- NA
aut_ids <- data.frame(unique = unique(authors$unique),
                      id = as.character(paste("aut", c(1:length(unique(authors$unique))), sep = "")), 
                      stringsAsFactors = FALSE)
nrow <- c(1:nrow(authors))
nrows <- c(1:nrow(aut_ids))
for(n in nrow){
  for (s in nrows){
    if(authors[n,7] == aut_ids[s,1]){
       authors[n,8] <- aut_ids[s,2]}
    else{}
}}
rm(aut_ids, nrow, nrows, n, s)
```


# Mapping

```{r all assessments completed by 2018, eval=FALSE}
library(rworldmap)
all <- authors[,-c(1,2,6,7)]
all <- unique(all)
all_num <- as.data.frame(table(all$CC))

countries_all <- joinCountryData2Map(all_num, joinCode = "ISO2", nameJoinColumn = "Var1")
cols <- RColorBrewer::brewer.pal(4, "YlGn")
mapCountryData(countries_all, mapRegion = "world",
               nameColumnToPlot = "Freq", numCats = 4, catMethod = "fixedWidth",
               colourPalette = cols, missingCountryCol = "white", oceanCol = "light blue",
               addLegend = T, mapTitle = "Where IPBES authors are from \n - all assessments completed by 2018 -")
```

```{r thematic assessments completed by 2018, eval=FALSE}
library(rworldmap)
thematic <- subset(authors, authors$Assessment %in% c("Pol", "Sce", "DLR"))
thematic <- thematic[,-c(1,2,6,7)]
thematic <- unique(thematic)
thematic_num <- as.data.frame(table(thematic$CC))
thematic_num <- subset(thematic_num, Freq != 0)

countries_thematic <- joinCountryData2Map(thematic_num, joinCode = "ISO2", nameJoinColumn = "Var1")
cols <- RColorBrewer::brewer.pal(4, "YlGn")
mapCountryData(countries_thematic, mapRegion = "world",
               nameColumnToPlot = "Freq", numCats = 4, catMethod = "fixedWidth",
               colourPalette = cols, missingCountryCol = "white", oceanCol = "light blue",
               addLegend = T, mapTitle = "Where IPBES authors are from \n - thematic assessments completed by 2018 -")
```

```{r LDR, eval=FALSE}
library(rworldmap)
LDR <- subset(authors, authors$Assessment %in% c("LDR"))
LDR <- LDR[,-c(1,2,6,7)]
LDR <- unique(LDR)
LDR_num <- as.data.frame(table(LDR$CC))
LDR_num <- subset(LDR_num, Freq != 0)

countries_LDR <- joinCountryData2Map(LDR_num, joinCode = "ISO2", nameJoinColumn = "Var1")
cols <- RColorBrewer::brewer.pal(4, "YlGn")
mapCountryData(countries_LDR, mapRegion = "world",
               nameColumnToPlot = "Freq", numCats = 4, catMethod = "fixedWidth",
               colourPalette = cols, missingCountryCol = "white", oceanCol = "light blue",
               addLegend = T, mapTitle = "Where IPBES authors are from \n - LDR assessment -")
```

```{r ECA, eval=FALSE}
library(rworldmap)
ECA <- subset(authors, authors$Assessment %in% c("ECA"))
ECA <- ECA[,-c(1,2,6,7)]
ECA <- unique(ECA)
ECA_num <- as.data.frame(table(ECA$CC))
ECA_num <- subset(ECA_num, Freq != 0)

countries_ECA <- joinCountryData2Map(ECA_num, joinCode = "ISO2", nameJoinColumn = "Var1")
cols <- RColorBrewer::brewer.pal(4, "YlGn")
mapCountryData(countries_ECA, mapRegion = "eurasia",
               nameColumnToPlot = "Freq", numCats = 4, catMethod = "fixedWidth",
               colourPalette = cols, missingCountryCol = "white", oceanCol = "light blue",
               addLegend = T, mapTitle = "Where IPBES authors are from \n - ECA assessment -")
```

```{r Asia-Pacific, eval=FALSE}
library(rworldmap)
Asi <- subset(authors, authors$Assessment %in% c("Asi"))
Asi <- Asi[,-c(1,2,6,7)]
Asi <- unique(Asi)
Asi_num <- as.data.frame(table(Asi$CC))
Asi_num <- subset(Asi_num, Freq != 0)

countries_Asi <- joinCountryData2Map(Asi_num, joinCode = "ISO2", nameJoinColumn = "Var1")
cols <- RColorBrewer::brewer.pal(4, "YlGn")
mapCountryData(countries_Asi, mapRegion = "world",
               nameColumnToPlot = "Freq", numCats = 4, catMethod = "fixedWidth",
               colourPalette = cols, missingCountryCol = "white", oceanCol = "light blue",
               addLegend = T, mapTitle = "Where IPBES authors are from \n - Asia-Pacific assessment -")
```

```{r Africa, eval=FALSE}
library(rworldmap)
Afr <- subset(authors, authors$Assessment %in% c("Afr"))
Afr <- Afr[,-c(1,2,6,7)]
Afr <- unique(Afr)
Afr_num <- as.data.frame(table(Afr$CC))
Afr_num <- subset(Afr_num, Freq != 0)

countries_Afr <- joinCountryData2Map(Afr_num, joinCode = "ISO2", nameJoinColumn = "Var1")
cols <- RColorBrewer::brewer.pal(4, "YlGn")
mapCountryData(countries_Afr, mapRegion = "world",
               nameColumnToPlot = "Freq", numCats = 4, catMethod = "fixedWidth",
               colourPalette = cols, missingCountryCol = "white", oceanCol = "light blue",
               addLegend = T, mapTitle = "Where IPBES authors are from \n - Africa assessment -")
```

```{r Americas, eval=FALSE}
library(rworldmap)
Ame <- subset(authors, authors$Assessment %in% c("Ame"))
Ame <- Ame[,-c(1,2,6,7)]
Ame <- unique(Ame)
Ame_num <- as.data.frame(table(Ame$CC))
Ame_num <- subset(Ame_num, Freq != 0)

countries_Ame <- joinCountryData2Map(Ame_num, joinCode = "ISO2", nameJoinColumn = "Var1")
cols <- RColorBrewer::brewer.pal(4, "YlGn")
mapCountryData(countries_Ame, mapRegion = "world",
               nameColumnToPlot = "Freq", numCats = 4, catMethod = "fixedWidth",
               colourPalette = cols, missingCountryCol = "white", oceanCol = "light blue",
               addLegend = T, mapTitle = "Where IPBES authors are from \n - The Americas assessment -")
```


# Netzwerkanalyse

```{r all, eval=FALSE}
authors <- authors[order(authors$Assessment, authors$Chapter, authors$Level, authors$CC, authors$Name),]
authors$subset <- apply(authors[,c(1,2)], 1, paste, collapse = " _ ")

nodes <- authors
nodes <- nodes[,-c(1,2,4,6,7,9)]
nodes <- unique(nodes)
nodes <- nodes[order(nodes$Name, nodes$CC),]
nodes <- nodes[,c(3,1,2)]
names(nodes) <- c("aut_id", "name", "country")

links <- data.frame(from = NA, to = NA, assessment = NA, chapter = NA)
assessment <- as.vector(unique(authors$subset))
assessment_num <- c(1:length(assessment))

for(n in assessment_num){
  subset <- subset(authors, authors$subset %in% assessment[n])
  rowssubset <- c(1:nrow(subset))
  for (r in rowssubset){
    t <- 1
    repeat{
      links <- rbind(links,
                     c(subset[r,8], subset[r+t,8], as.character(subset[r,1]), subset[r,2]),
                     stringsAsFactors = FALSE)
      t <- t+1
      if (t==max(rowssubset)){break}}
  }
}
links <- subset(links, !is.na(links$to))
rm(assessment, assessment_num, n, r, t, rowssubset)

library(igraph)
ntw <- graph_from_data_frame(d = links, vertices = nodes, directed = F)

V(ntw)$degree <- degree(ntw)
V(ntw)$betweenness <- betweenness(ntw, directed = F)

V(ntw)$vertex.size <- 5 * V(ntw)$betweenness / max(V(ntw)$betweenness) + 2

betwennesscol <- RColorBrewer::brewer.pal(9, "YlOrRd")
V(ntw)$vertex.col[V(ntw)$vertex.size == 2] <- "light grey" # betwennesscol[3]
V(ntw)$vertex.col[V(ntw)$vertex.size > 2] <- betwennesscol[4] # 147 - 121
V(ntw)$vertex.col[V(ntw)$vertex.size > 3] <- betwennesscol[5] # 26 - 18
V(ntw)$vertex.col[V(ntw)$vertex.size > 4] <- betwennesscol[6] # 8 - 4
V(ntw)$vertex.col[V(ntw)$vertex.size > 5] <- betwennesscol[7] # 4 - 3
V(ntw)$vertex.col[V(ntw)$vertex.size > 6] <- betwennesscol[8] # 1

assessmentcol <- c("#39ca00","#1e1272","#a4d721","#008cf4","#2be199","#ff60b3","#01d2f8") #RColorBrewer::brewer.pal(7, "Set2")
E(ntw)$edge.col[E(ntw)$assessment == "Pol"] <- assessmentcol[1]
E(ntw)$edge.col[E(ntw)$assessment == "Sce"] <- assessmentcol[2]
E(ntw)$edge.col[E(ntw)$assessment == "LDR"] <- assessmentcol[3]
E(ntw)$edge.col[E(ntw)$assessment == "Afr"] <- assessmentcol[4]
E(ntw)$edge.col[E(ntw)$assessment == "Asi"] <- assessmentcol[5]
E(ntw)$edge.col[E(ntw)$assessment == "Ame"] <- assessmentcol[6]
E(ntw)$edge.col[E(ntw)$assessment == "ECA"] <- assessmentcol[7]

lyout <- layout.fruchterman.reingold(ntw) #layout.auto(ntw)
plot(ntw, vertex.size = V(ntw)$vertex.size, vertex.color = V(ntw)$vertex.col,
     vertex.label = NA, vertex.label.family = "Calibri", vertex.label.cex = 0.5,
     vertex.frame.color = NA, vertex.label.color = "black",
     edge.arrow.size = 0, edge.color = E(ntw)$edge.col,
     layout = lyout)
```
