---
title: "Soziale Netzwerkanalyse: Projekte"
author: "Jonas Geschke"
date: "2018"
header-includes:
   - \usepackage{longtable}
output:
  pdf_document:
    toc: yes
  documentclass: article
  html_document:
    toc: yes
  classoption: a4paper
  graphics: yes
---

# Einleitung
Dieses ist das Skript der Netzwerkanalyse zu NeFo auf Grundlage der von DFG und der verschiedenen Bundesressorts geförderten Projekte. Das Skrpit ist verfügbar unter https://github.com/JonasGeschke/nefo
Die Netzwerkanalyse selbst ist verfügbar unter XXX

https://stackoverflow.com/questions/35960170/igraph-add-to-geographic-map
https://stackoverflow.com/questions/30647537/using-geo-coordinates-as-vertex-coordinates-in-the-igraph-r-package/30671830#30671830
http://kateto.net/network-visualization


# Einstellungen

```{r set wd - CHOOSE, eval=FALSE}
# If your working directory is not already specified because you are running this
# script within a project, you will need to use the setwd() function below to set
# the path of your working directory. In order to do this just copy the path
# between the quote signs.
# Please note: The different levels of the path need to be separated by slashes
# ("/"), not by backslashes ("\") which are the windows default.
# 
# setwd("")

#setwd("/Volumes/NO NAME/MfN/Netzwerkanalyse_Projekte/R") # Stick
#setwd("~/HiDrive/users/dojo-drive-jonas/MfN/R") # HiDrive
setwd("Z:/Benutzer/Jonas.Geschke/Netzwerkanalyse_Projekte/R") # Buero
```

```{r install packages, eval=FALSE}
# Installing required packages if not installed yet
if("statnet" %in% rownames(installed.packages())   == FALSE){
  install.packages("statnet")}
if("network" %in% rownames(installed.packages())   == FALSE){
  install.packages("network")}
if("sna" %in% rownames(installed.packages())   == FALSE){
  install.packages("sna")}
if("igraph" %in% rownames(installed.packages())   == FALSE){
  install.packages("igraph")}
if("xts" %in% rownames(installed.packages())   == FALSE){
  install.packages("xts")}
if("xlsx" %in% rownames(installed.packages())   == FALSE){
  install.packages("xlsx")}
if("dplyr" %in% rownames(installed.packages())   == FALSE){
  install.packages("dplyr")}
if("rgl" %in% rownames(installed.packages())   == FALSE){
  install.packages("rgl")}
if("extrafont" %in% rownames(installed.packages())   == FALSE){
  install.packages("extrafont")}
if("circlize" %in% rownames(installed.packages())   == FALSE){
  install.packages("circlize")}
if("RColorBrewer" %in% rownames(installed.packages())   == FALSE){
  install.packages("RColorBrewer")}
if("lubridate" %in% rownames(installed.packages())   == FALSE){
  install.packages("lubridate")}
if("Rcrawler" %in% rownames(installed.packages())   == FALSE){
  install.packages("Rcrawler")}
if("readr" %in% rownames(installed.packages())   == FALSE){
  install.packages("readr")}
if("shiny" %in% rownames(installed.packages())   == FALSE){
  install.packages("shiny")}
if("shinythemes" %in% rownames(installed.packages())   == FALSE){
  install.packages("shinythemes")}
```

```{r set additional functions, eval=FALSE}
as.numeric.factor <- function(x) {as.numeric(levels(x))[x]}

'%!in%' <- function(x,y)!('%in%'(x,y))

subset_projects <- function(keywords = c(keywords), database = projects){

projects <- database
projects_filter <- projects
projects_filter$filter <- tolower(paste(projects_filter$projekt,
                                        projects_filter$verbundprojekt,
                                        projects_filter$kategorie,
                                        sep = "_"))

biodiv <- projects_filter[-c(1:nrow(projects_filter)),]
keywords_num <- c(1:length(keywords))
for(k in keywords_num){
biodiv <- rbind(biodiv,
                projects_filter[grep(keywords[k], projects_filter$filter),])
}
rm(projects_filter, k, keywords_num)

biodiv <- biodiv[order(biodiv$foerderer, 
                       strptime(biodiv$von,format="%d.%m.%Y"), 
                       biodiv$verbundprojekt, 
                       biodiv$projekt),]
duplicated_test <- integer(0)
if(identical(which(duplicated(biodiv)), duplicated_test) == FALSE){
  biodiv <- biodiv[-which(duplicated(biodiv)),]}
rm(duplicated_test)

#allocate_ids cut here

biodiv <- biodiv[,-c(17)]

return(biodiv)
}

subset_foerderzeitraum <- function(years = c(years), foerderkatalog = Gdata){

Gdata <- foerderkatalog
Gdata <- rbind(Gdata, gepris)

Gdata$foerderjahre <- NA
Gdata <- Gdata[,c(1:2,17,3:16)]

Gdata$von[(nrow(foerderkatalog)+1):nrow(Gdata)] <- 
  paste("01.01.", Gdata$von[(nrow(foerderkatalog)+1):nrow(Gdata)], sep="")
Gdata$bis[(nrow(foerderkatalog)+1):nrow(Gdata)] <- 
  paste("01.01.", Gdata$bis[(nrow(foerderkatalog)+1):nrow(Gdata)], sep="")

jahre <- c(as.numeric(format(as.Date(Gdata$bis, "%d.%m.%Y"), "%Y")) - 
             as.numeric(format(as.Date(Gdata$von, "%d.%m.%Y"), "%Y")))
nrow <- c(1:nrow(Gdata))

for(n in nrow){
  p <- 1
  period <- c(seq(from = as.numeric(format(as.Date(Gdata[n,4], "%d.%m.%Y"), "%Y")), 
                        length.out = (jahre[n]+1)))
  period_num <- c(1:length(period))
  Gdata[n,3] <- paste(period, collapse = "_")
}
rm(jahre, nrow, n, p, period, period_num)

if(years == "all"){
  Gdata_new <- Gdata}
else{
Gdata_new <- Gdata[-c(1:nrow(Gdata)),]
years_num <- c(1:length(years))
for(y in years_num){
Gdata_new <- rbind(Gdata_new,
                   Gdata[grep(as.character(years[y]), Gdata$foerderjahre),])
}
rm(y, years_num, Gdata)

duplicated_test <- integer(0)
if(identical(which(duplicated(Gdata_new)), duplicated_test) == FALSE){
  Gdata_new <- Gdata_new[-which(duplicated(Gdata_new)),]}
rm(duplicated_test)
}

Gdata_new <- Gdata_new[,-3]

return(Gdata_new)
}

allocate_ids <- function(dataset = Gdata){
  biodiv <- dataset
  
  inst_ids <- data.frame(unique = unique(biodiv$institution),
                      id = as.character(paste("inst", c(1:length(unique(biodiv$institution))), sep = "")), 
                      stringsAsFactors = FALSE)
nrow <- c(1:nrow(biodiv))
nrows <- c(1:nrow(inst_ids))
for(n in nrow){
  for (s in nrows){
    if(biodiv[n,9] == inst_ids[s,1]){
       biodiv[n,8] <- inst_ids[s,2]}
    else{}
}}
rm(inst_ids, nrow, nrows, n, s)

biodiv_einzeln <- subset(biodiv, is.na(biodiv$verbundprojekt))
biodiv_verbund <- subset(biodiv, !is.na(biodiv$verbundprojekt))
biodiv_einzeln$unique <- paste(biodiv_einzeln$von, 
                               biodiv_einzeln$projekt, 
                               sep = "_")
biodiv_verbund$unique <- paste(biodiv_verbund$von, 
                               biodiv_verbund$verbundprojekt, 
                               sep = "_")
proj_id <- data.frame(unique = unique(biodiv_verbund$unique),
                      id = as.character(paste("proj", c(1:length(unique(biodiv_verbund$unique))), sep = "")), 
                      stringsAsFactors = FALSE)
nrow <- c(1:nrow(biodiv_verbund))
nrows <- c(1:nrow(proj_id))
for(n in nrow){
  for (s in nrows){
    if(biodiv_verbund[n,17] == proj_id[s,1]){
       biodiv_verbund[n,5] <- proj_id[s,2]}
    else{}
}}
rm(proj_id, nrow, nrows, n, s)
proj_id <- data.frame(unique = unique(biodiv_einzeln$unique),
                      id = as.character(
                        paste("proj", 
                              c((length(unique(biodiv_verbund$unique))+1):
                                (length(unique(biodiv_einzeln$unique))+length(unique(biodiv_verbund$unique)))
                                 ), sep = "")), 
                      stringsAsFactors = FALSE)
nrow <- c(1:nrow(biodiv_einzeln))
nrows <- c(1:nrow(proj_id))
for(n in nrow){
  for (s in nrows){
    if(biodiv_einzeln[n,17] == proj_id[s,1]){
       biodiv_einzeln[n,5] <- proj_id[s,2]}
    else{}
}}
rm(proj_id, nrow, nrows, n, s)
biodiv <- rbind(biodiv_verbund, biodiv_einzeln)
rm(biodiv_einzeln, biodiv_verbund)
biodiv <- biodiv[,-c(17)]

return(biodiv)
}
```


# Rohdaten

```{r Crawling GEPRIS - Projekte, eval=FALSE}
library(Rcrawler)

keywords <- "biodiv*+OR+%26quot%3Bbiologische*+vielfalt%26quot%3B+OR+%26quot%3Bbiological+diversity%26quot%3B" # * = und Anhang | +OR+ = OR | + = Leerzeichen | %26quot%3B = Anführungsstriche
Suche <- paste("http://gepris.dfg.de/gepris/OCTOPUS?context=project&findButton=Finden&hitsPerPage=10000&keywords_criterion=", keywords, "&language=de&nurProjekteMitAB=false&task=doSearchSimple", sep = "")

Suche <- "http://gepris.dfg.de/gepris/OCTOPUS?context=projekt&findButton=historyCall&hitsPerPage=10000&index=0&keywords_criterion=biodiv*+OR+%26quot%3Bbiologische*+vielfalt%26quot%3B+OR+%26quot%3Bbiological+diversity%26quot%3B&nurProjekteMitAB=false&orderBy=name&task=doSearchSimple"

\dontrun{
INDEX <- data.frame("Id"=NA, "Url"=NA, "Stats"=NA, "Level"=NA, "OUT"=NA, "IN"=NA, "Http Resp"=NA, "Content Type"=NA, "Encoding"=NA, "Accuracy"=NA)
for(a in letters){
  Suche <- paste("http://gepris.dfg.de/gepris/OCTOPUS?context=projekt&findButton=historyCall&hitsPerPage=500000&index=0&keywords_criterion=", a, "*&task=doSearchSimple", sep = "")
  INDEX <- rbind(INDEX,
                 Rcrawler(Suche, no_cores = 1, no_conn = 1,
                          dataUrlfilter = c("/gepris/projekt/"),
                          crawlUrlfilter = c("/gepris/projekt/"),
                          ignoreUrlParams = c("/ergebnisse", 
                                              "?language", 
                                              "?displayMode", 
                                              "?fontSize", 
                                              "?contrast"))
                 )
}
}

Rcrawler(Suche, no_cores = 2, no_conn = 2, #MaxDepth = 1,
         dataUrlfilter = c("/gepris/projekt/"),
         crawlUrlfilter = c("/gepris/projekt/"),
         ignoreUrlParams = c("/ergebnisse", "?language", "?displayMode", "?fontSize", "?contrast"))
```

```{r Scraping GEPRIS - Projekte, eval=FALSE}
library(Rcrawler)

files <- c(1:length(list.files(path = paste(getwd(), 
                                            "/gepris.dfg.de-111357", 
                                            sep=""))))

DATA <- list()
for(a in files){
  DATA[[a]] <- ContentScraper(HTmlText = paste(paste(getwd(), 
                                            "/gepris.dfg.de-111357/", 
                                            sep=""), a," .html", sep=""),
                              XpathPatterns = c("/html/body/div[1]/div/div[3]/div[1]/div/div/div[2]/div[1]/div[1]/h3",
                                                "//*[@id='projekttext']",
                                                "//*[@class='name']",
                                                "//*[@class='value']"),
                              ManyPerPattern = TRUE,
                              encod = "UTF-8")
}
gepris <- data.frame(do.call("rbind", DATA))

title <- unlist(lapply(DATA, `[[`, 1))
title <- gsub("[\r\n\t]", "", title)
title <- trimws(title, which = c("both"))
title <- trimws(gsub("\\s+", " ", title))
gepris$X1 <- title
descr <- unlist(lapply(DATA, `[[`, 2))
descr <- gsub("[\r\n\t]", "", descr)
descr <- trimws(descr, which = c("both"))
descr <- trimws(gsub("\\s+", " ", descr))
gepris$X2 <- descr
column_names <- unlist(lapply(DATA, `[[`, 3))
column_names <- gsub("[\r\n\t]", "", column_names)
column_names <- trimws(column_names, which = c("both"))
column_names <- trimws(gsub("\\s+", " ", column_names))

contentno <- vector()
for(p in files){
  contentno <- c(contentno, length(DATA[[p]][[3]]))}
max(contentno)

add_columns <- c(ncol(gepris)+1:length(unique(column_names)))
gepris[,add_columns] <- NA
names(gepris) <- c("titel", "descr", "name", "value", unique(column_names))

for(n in files){
  name <- DATA[[n]][[3]]
  name <- gsub("[\r\n\t]", "", name)
  name <- trimws(name, which = c("both"))
  name <- trimws(gsub("\\s+", " ", name))
  value <- DATA[[n]][[4]]
  value <- gsub("[\r\n\t]", "", value)
  value <- trimws(value, which = c("both"))
  value <- trimws(gsub("\\s+", " ", value))
  check <- c(1:length(DATA[[n]][[3]]))
  for(c in check){
    for(a in add_columns){
    if(names(gepris[a]) == name[c]){gepris[n,a] <- value[c]}
    }
  }
}

Raw_gepris <- gepris[,-c(3,4)]

#write.csv2(gepris, file = "gepris.csv")

rm(a, add_columns, c, check, column_names, contentno, descr, files, n, name, p, title, value, gepris)
```

```{r Laden und Vorbereitung des Förderkatalogs, eval=FALSE}
library(xlsx)
## Load raw data
#Raw_projects_FA <- read.csv2("Daten/Suchergebnisse_FA_form.csv", sep=";", dec=",", header=T, stringsAsFactors=F)
#Raw_projects_FB <- read.csv2("Daten/Suchergebnisse_FB_form.csv", sep=";", dec=",", header=T, stringsAsFactors=F)
#Raw_projects_FC <- read.csv2("Daten/Suchergebnisse_FC_form.csv", sep=";", dec=",", header=T, stringsAsFactors=F)
#Raw_projects_FD <- read.csv2("Daten/Suchergebnisse_FD_form.csv", sep=";", dec=",", header=T, stringsAsFactors=F)

Raw_projects_gesamt <- read.csv2("Suchliste_gesamt_form.csv", sep=";", dec=",", header=T, na.strings = "", stringsAsFactors=F) # Abgerufen am 9.1.19

#projects <- rbind(Raw_projects_FA, Raw_projects_FB, Raw_projects_FC, Raw_projects_FD)
projects <- Raw_projects_gesamt

projects <- projects[,-c(1,3,5,7,8,9,10,13,14,15,16)]
projects <- projects[complete.cases(projects[,c(1:3)]),]
projects$inst_id <- NA
projects$proj_id <- NA
projects <- projects[,c(1,2,10,11,16,7,14,15,3,4,5,6,13,9,8,12)]

names(projects) <- c("foerderer", "pt", "von", "bis", "proj_id", "projekt",
                     "verbundprojekt", "inst_id", "institution",
                     "land", "durchfuehrung", "durchfuehrung_land",
                     "topic", "kategorie", "kategorie_num", "budget")

projects <- projects[order(projects$foerderer, projects$von, projects$bis),]

# Korrektur der Fraunhofer-Gesellschaft
#projects <- subset(projects, projects$institution == "Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V.")
#nrow <- c(1:nrow(projects))
#for(n in nrow){
#  if(projects[n,9] == "Fraunhofer-Gesellschaft zur Förderung der angewandten Forschung e.V."){
#    projects[n,9] <- projects[n,11]
#  }
#}
#rm(nrow, n)
```

```{r Abkürzungen, eval=FALSE}
abbr <- read.csv2("Forschungsatlas_abbr.csv", sep=";", dec=",", header=T, stringsAsFactors=F)
abbr <- read.csv2("kuerzel_Donnerstag.csv", sep=";", dec=",", header=T, stringsAsFactors=F)
abbr <- abbr[,-1]

kuerzel <- data.frame(abbr = NA, inst = unique(Gdata$institution))
nrow_kuerzel <- c(1:nrow(kuerzel))
nrow_abbr <- c(1:nrow(abbr))
for(i in nrow_kuerzel){
  for(j in nrow_abbr){
    if(kuerzel[i,2] == abbr[j,2]){
      kuerzel[i,1] <- abbr[j,3]
    }
  }
}
rm(nrow_kuerzel, nrow_abbr)
#write.csv2(kuerzel, file = "kuerzel.csv")
```


# Vorbereitung der Daten

```{r transform gepris, eval=FALSE}
gepris <- projects
gepris <- gepris[-c(1:nrow(gepris)),]

zeilen <- c(1:nrow(Raw_gepris))
spalten <- c(1:ncol(Raw_gepris))

gepris[zeilen,] <- NA

gepris$foerderer <- "DFG"
gepris$projekt <- Raw_gepris[,1] # titel
gepris$verbundprojekt <- Raw_gepris[,13] # Teilprojekt zu
gepris$topic <- Raw_gepris[,6] # DFG-Verfahren
gepris$kategorie <- Raw_gepris[,3] # Fachliche Zuordnung

laufzeit <- data.frame("von" = as.character(NA), 
                       "bis" = as.character(NA),
                       "förderung" = as.character(Raw_gepris[,4]), # Förderung
                       stringsAsFactors = FALSE)
laufzeit$von <- readr::parse_number(laufzeit[,3])
for(r in zeilen){
  if(grepl("in", laufzeit[r,3])){
    laufzeit[r,2] <- laufzeit[r,1]}
  if(grepl("seit", laufzeit[r,3])){
    laufzeit[r,2] <- format(Sys.Date(), "%Y")}
  if(grepl("bis", laufzeit[r,3])){
    laufzeit[r,2] <- substr(laufzeit[r,3], 24, 27)}
}
gepris$von <- laufzeit[,1] # von
gepris$bis <- laufzeit[,2] # bis
rm(laufzeit,r)

antragsteller <- data.frame("antragsteller" = as.character(NA), 
                       "title" = as.character(Raw_gepris[,1]),
                       stringsAsFactors = FALSE)
antragsteller[,1] <- paste(Raw_gepris[,9], # Antragstellende Institution
                           Raw_gepris[,11], # Antragsteller
                           Raw_gepris[,12], # Antragstellerin
                           Raw_gepris[,20], # Antragsteller
                           Raw_gepris[,24], # Antragstellerinnen/Antragsteller
                           Raw_gepris[,25], # Mitanstragstellerin
                           Raw_gepris[,36], # Mitantragstellende Institution
                           Raw_gepris[,41], # Mitantragsteller
                           Raw_gepris[,42], # Mitantragstellerinnen/Mitantragsteller
                           Raw_gepris[,49], # Antragstellerinnen
                           sep = " _ ")
antragsteller[,1] <- gsub("NA _ ", "", antragsteller[,1])
antragsteller[,1] <- gsub("_ NA", "", antragsteller[,1])
gepris$institution <- antragsteller[,1]
rm(antragsteller)

#gepris <- gepris[-which(gepris[,9] == "NA"),]
gepris <- gepris[-which(grepl("[0-9]:", substr(gepris$projekt, 1, 10))),]
#length(unique(gepris$verbundprojekt))

#### Antragstellende Institution filtern

rm(spalten, zeilen)
```

```{r Analyse des Leistungsplans # EDIT, eval=FALSE}
leistungsplan <- projects[,c(14,15)]
leistungsplan <- leistungsplan[-which(duplicated(leistungsplan)),]
leistungsplan <- leistungsplan[-which(is.na(leistungsplan$kategorie)),]
leistungsplan <- leistungsplan[order(leistungsplan$kategorie_num),]

library(tidytext)
library(textreadr)
library(dplyr)
library(tidyr)

stopwords_de <- get_stopwords(language = "de")

lplan_df <- data_frame(line = 1:nrow(leistungsplan), text = leistungsplan$kategorie)
tidy_lplan <- lplan_df %>% unnest_tokens(word, text, to_lower = T) %>% anti_join(get_stopwords(language = "de"))
tidy_lplan <- tidy_lplan[-which(duplicated(tidy_lplan)),]
tidy_lplan$document <- "lplan"
lplan <- tidy_lplan %>% count(word, sort = TRUE)

# Load NBS

NBS_raw <- read_pdf("Daten/nbs.pdf")
NBS_raw <- NBS_raw$text
#NBS_raw <- read_document("Daten/nbs_plaintext.docx")
NBS_df <- data_frame(line = 1:length(NBS_raw), text = NBS_raw)
tidy_NBS <- NBS_df %>% unnest_tokens(word, text, to_lower = T) %>% anti_join(get_stopwords(language = "de"))
tidy_NBS$document <- "NBS"
NBS <- tidy_NBS %>% count(word, sort = TRUE)

# Load NSO
NSO_raw <- read_pdf("Daten/nso.pdf")
NSO_raw <- NSO_raw$text
#NSO_raw <- read_document("Daten/nso_plaintext.docx")
NSO_df <- data_frame(line = 1:length(NSO_raw), text = NSO_raw)
tidy_NSO <- NSO_df %>% unnest_tokens(word, text, to_lower = T) %>% anti_join(get_stopwords(language = "de"))
tidy_NSO$document <- "NSO"
NSO <- tidy_NSO %>% count(word, sort = TRUE)

rm(lplan_df, NBS_df, NSO_df, NBS_raw, NSO_raw, tidy_lplan, tidy_NBS, tidy_NSO, stopwords_de)
# Match Strategies with Leistungsplan
lplan$NBS <- NA
lplan$NSO <- NA

nrow_lplan <- c(1:nrow(lplan))
nrow_nbs <- c(1:nrow(NBS))
nrow_nso <- c(1:nrow(NSO))
for(n in nrow_lplan){
  for(b in nrow_nbs){
    if(lplan[n,1] == NBS[b,1]){
      lplan[n,3] <- NBS[b,2]
    }
  }
  for(o in nrow_nso){
    if(lplan[n,1] == NSO[o,1]){
      lplan[n,4] <- NBS[o,2]
    }
  }
}
rm(nrow_lplan, nrow_nbs, nrow_nso, n, b, o)

#write.csv2(lplan, file = "leistungsplan_stichworte.csv")

lplan_na <- lplan[which(is.na(lplan$NBS) & is.na(lplan$NSO)),]
#write.csv2(lplan_cut, file = "leistungsplan_stichworte_strategien.csv")

NAs <- lplan_na$word

raus <- leistungsplan$kategorie
```

```{r Förderkatalog subset by keywords, eval=FALSE}
#biodiv <- subset_projects(keywords = c("biodiv"))
biodivbiolvielfalt <- subset_projects(keywords = c("biodiv", 
                                                   "biologische vielfalt", "biologischen vielfalt",
                                                   "biological diversity"))

#monitoring <- subset_projects(keywords = c("biodiv", "biologische vielfalt", "biologischen vielfalt",
                                           "biological diversity", "monitoring"))

```

```{r Auswahl Datensatz (+gepris) und Förderzeitraum, eval=FALSE}
Gdata <- subset_foerderzeitraum(years = c("all"), 
                               foerderkatalog = biodivbiolvielfalt)
Gdata <- subset_foerderzeitraum(years = c(2007, 2008, 2009, 2010, 2011, 
                                         2012, 2013, 2014, 2015, 2016, 
                                         2017, 2018), 
                               foerderkatalog = biodivbiolvielfalt)

#Gdata <- subset_foerderzeitraum(years = c(2019), foerderkatalog = monitoring)
```


# Ergänzung durch Forschungsverbünde

```{r Laden der Rohdaten und Vorbereitung der Daten # EDIT, eval=FALSE}
## Load raw data
Raw_forschungsnetzwerke <- read.csv2("Daten/forschungsnetzwerk.csv", sep=",", dec=".", header=T, encoding="UTF-8")

## Prepare dataset "FN"
Gdata_FN <- Raw_forschungsnetzwerke
names(Gdata_FN) <- c("inst", "abbr", "BeGenDiv", "BBIB", "BioFrankfurt", "BION", "iDiv", "Ecornet", "FVB", "GBIF-D", "GFBIO", "HIFMB", "KDM", "LVB")
Gdata_FN <- Gdata_FN[,-c(7,9,10,11)] #Delete iDiv, FVB, GBIF-D, GFBIO
rownames(Gdata_FN) <- Gdata_FN[,2] #Inst oder abbr as rownames
Gdata_FN <- Gdata_FN[,-c(1,2)] #Delete inst and abbr
Gdata_FN <- Gdata_FN[,c(8,4,2,7,3,5,1,6)] #Order by number of members

Gdata_FN$BeGenDiv <- as.numeric(Gdata_FN$BeGenDiv)
Gdata_FN$BBIB <- as.numeric(Gdata_FN$BBIB) #raus?
Gdata_FN$BioFrankfurt <- as.numeric(Gdata_FN$BioFrankfurt)
Gdata_FN$BION <- as.numeric(Gdata_FN$BION)
Gdata_FN$iDiv <- as.numeric(Gdata_FN$iDiv) #raus
Gdata_FN$Ecornet <- as.numeric(Gdata_FN$Ecornet)
Gdata_FN$GFBIO <- as.numeric(Gdata_FN$GFBIO) #raus
Gdata_FN$HIFMB <- as.numeric(Gdata_FN$HIFMB)
Gdata_FN$KDM <- as.numeric(Gdata_FN$KDM)
Gdata_FN$LVB <- as.numeric(Gdata_FN$LVB)
Gdata_FN$`GBIF-D` <- as.numeric(Gdata_FN$`GBIF-D`) #raus
```


# Netzwerkanalyse

```{r Vorbereitung, eval=FALSE}
Gdata <- allocate_ids(Gdata)

inst <- data.frame(id = Gdata$inst_id,
                   abbr = NA,
                   name = Gdata$institution,
                   type = "Institution",
                   ressort = NA,
                   pt = NA,
                   leistungsplansystematik = NA,
                   budget = NA,
                   stringsAsFactors = FALSE)
proj <- data.frame(id = Gdata$proj_id,
                   abbr = NA,
                   name = Gdata$projekt,
                   type = "Projekt",
                   ressort = Gdata$foerderer,
                   pt = Gdata$pt,
                   leistungsplansystematik = Gdata$kategorie,
                   budget = NA,
                   stringsAsFactors = FALSE)
nodes <- rbind(inst,proj)
nodes <- nodes[-which(duplicated(nodes$id)),]
nodes_num <- c(1:nrow(nodes))
for(n in nodes_num){
  if(nodes[n,4] == "Projekt"){
    nodes[n,8] <- sum(Gdata[(Gdata$proj_id == nodes[n,1]), 17])
  }
}
for(n in nodes_num){
  if(nodes[n,3] %in% abbr$inst){
    nodes[n,2] <- abbr[which(abbr[,2] == nodes[n,3]),1]
  }
}
rm(inst, proj, nodes_num, n)

str(nodes)

links <- Gdata
links <- links[,c(8,5,9,10,6,7,1:4,11:16)] #links[,c(9,6,10,11,7,8,1,2,3,4,5,12,13,14,15,16,17)]
names(links)[c(1,2)] <- c("from", "to")
links_dupl <- links[c("from", "to")]
links <- links[-which(duplicated(links_dupl)),]
rm(links_dupl)

ntw <- igraph::graph_from_data_frame(d = links, vertices = nodes, directed = F)
```

```{r Visualisierung, eval=FALSE}
library(igraph)

V(ntw)$degree <- degree(ntw)
V(ntw)$betweenness <- betweenness(ntw, directed = F)

V(ntw)$plotname <- NA
V(ntw)$plotname[V(ntw)$type == "Institution"] <- nodes$abbr[V(ntw)$type == "Institution"]
V(ntw)$plotname[as.numeric(V(ntw)$degree[V(ntw)$type == "Institution"]) == 1] <- NA
V(ntw)$vertex.size[V(ntw)$type == "Institution"] <- 3
V(ntw)$vertex.size[V(ntw)$type == "Projekt"] <- 2
  
coul <- RColorBrewer::brewer.pal(5, "YlOrBr")
palette <- as.numeric(V(ntw)$degree[V(ntw)$type == "Institution"])
palette[which(palette == 1)] <- 1
palette[which(palette %in% c(2:5))] <- 2
palette[palette %in% c(6:10)] <- 3
palette[palette %in% c(11:15)] <- 4
palette[palette > 15] <- 5
farben <- coul[palette]

V(ntw)$vertex.label.cex <- 2 * V(ntw)$betweenness / max(V(ntw)$betweenness) + 0.5
V(ntw)$vertex.col[V(ntw)$type == "Institution"] <- farben

#budget <- c("grey90", "dark grey", "black") #"light blue", "cornflowerblue", "dark blue")
#V(ntw)$vertex.frame.col[V(ntw)$budget < 1000000] <- budget[1]
#V(ntw)$vertex.frame.col[V(ntw)$budget >= 1000000] <- budget[2]
#V(ntw)$vertex.frame.col[V(ntw)$budget >= 5000000] <- budget[3]

foerderer <- c("grey", "goldenrod4", "forestgreen", "darkorchid", "blue") # to do
V(ntw)$vertex.col[V(ntw)$foerderer == "BMBF"] <- foerderer[1]
V(ntw)$vertex.col[V(ntw)$foerderer == "BMEL"] <- foerderer[2]
V(ntw)$vertex.col[V(ntw)$foerderer == "BMU"] <- foerderer[3]
V(ntw)$vertex.col[V(ntw)$foerderer == "BMWi"] <- foerderer[4]
V(ntw)$vertex.col[V(ntw)$foerderer == "DFG"] <- foerderer[5] # to do

lyout <- layout.auto(ntw) #layout.fruchterman.reingold(ntw)

plot(ntw, vertex.size = V(ntw)$vertex.size, vertex.color = V(ntw)$vertex.col,
     vertex.label = V(ntw)$plotname, vertex.label.family = "Calibri", vertex.label.cex = V(ntw)$vertex.label.cex,
     vertex.frame.color = "light grey", vertex.label.color = "black",
     edge.arrow.size = 0, edge.color = "gainsboro",
     layout = lyout,
     main = "Projektbasierte Vernetzung in der Biodiversitätsforschung 2007-2018")
legend(-1.6,-0.7, title = "Institution: Degree", legend = c("1", "2-5", "6-10", "11-15", ">15"), fill = coul)
legend(1,-0.7, title = "Projekt: Förderer", legend = c("BMBF", "BMEL", "BMU", "BMWi", "DFG"), fill = foerderer)
#legend(-1.6,1.2, title = "Institution: Degree", legend = c("1", "2-5", "6-10", "11-15", ">15"), fill = coul)
#legend(1,1.2, title = "Projekt: Förderer", legend = c("BMBF", "BMEL", "BMU", "BMWi", "DFG"), fill = foerderer)
text(0,1.1, "Schriftgröße = Betweenness")

Gdata_sna <- cbind(nodes,
                   degree = V(ntw)$degree,
                   betweenness = V(ntw)$betweenness)
```



